name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v3
      with:
        python-version: "3.6.7"
        
    - name: Install dependencies
      run: make install

    - name: Run test
      run: make test
